### ISSUE TITLE
Define a minimal working configuration

### ISSUE THREAD

**Issue by andrewgait** [UoMResearchIT/PhotonPropagation-Issue-Only#10]
We need to define a minimal working configuration between Mitsuba 3 and Geant4 that we want to get running, which can then be split into individual tasks/issues as appropriate.

**Comment by ianhinder** [comment]
Need to discuss this with Marco.

**Comment by gersabec** [comment]
In the Year 1 project, we worked with the so-called simplified RICH geometry, which would be a useful minimal working configuration. It consists of a photon source with configurable point of origin and direction (we ignored wavelength dependance), two mirrors and a detection plane in the shape of a pixelated rectangle. This is sufficiently non-trivial that we test photon transport and resolution on the detector side, but doesn't have other complications (e.g. we can assume that everything is in vacuum and we can thus ignore photon interactions with the medium they travel through).

**Comment by andrewgait** [comment]
A minimal working configuration was defined and work to set this up will be done in #12.
