### ISSUE TITLE
Run an example with the customised photon_emitter

### ISSUE THREAD

**Issue by andrewgait** [UoMResearchIT/PhotonPropagation-Issue-Only#11]
Some current scripts I have access to do not work because the photon_emitter described in [Davis et al (2023)](https://arxiv.org/abs/2309.12496) isn't available in standard Mitsuba 3.  Finding this code (and possibly submitting it to be included in Mitsuba 3) would be helpful.

> I am able to run most of the examples in the [MitsubaMphys](https://github.com/gersabec/MitsubaMphys/) repository (in both python files and Jupyter notebooks), but I am having trouble with the script in `final_simulation/python_scene.py` - I think, from doing a bit of reading up, because this is using a custom emitter (`photon_emitter`) which must be in an updated / forked version of Mitsuba as it's not in the standard version.

_Originally posted by @andrewgait in https://github.com/UoMResearchIT/PhotonPropagation-Issue-Only/issues/5#issuecomment-2117561705_

**Comment by gersabec** [comment]
Here's a pointer to the photon_emitter code:
https://github.com/yangocean-sudo/mitsuba3-manchester/blob/master/src/emitters/photon_emitter.cpp

**Comment by gersabec** [comment]
Olivia's repository also contains a new implementation of the emitter in
https://github.com/OliviaBorgstrom/mitsuba3-olivia/blob/master/src/emitters/photon_emitter_olivia.cpp
and a test in
https://github.com/OliviaBorgstrom/mitsuba3-olivia/blob/master/olivia/Experiment2-singlePhoton.ipynb

**Comment by andrewgait** [comment]
> Olivia's repository also contains a new implementation of the emitter in https://github.com/OliviaBorgstrom/mitsuba3-olivia/blob/master/src/emitters/photon_emitter_olivia.cpp and a test in https://github.com/OliviaBorgstrom/mitsuba3-olivia/blob/master/olivia/Experiment2-singlePhoton.ipynb

After some work I am now able to run the example in MitsubaMphys with `photon_emitter` and the example using Olivia's implementation `photon_emitter_olivia`.  I'll now move on to checking how this example matches with our suggested minimal working configuration in #10 which is being worked on in #12.

**Comment by andrewgait** [comment]
To expand a little on the "some work" mentioned in the above comment, I found errors when trying to build mitsuba (using `pip install .`) from both the mitsuba-manchester and mistuba-olivia repos.  Eventually I worked out that in the mitsuba-olivia case it was the same error as detailed here: https://github.com/mitsuba-renderer/mitsuba3/issues/1147, and the solution was to cap the version of pybind11.

**Comment by andrewgait** [comment]
Examples have been run using the customised photon emitters so this can be closed.
