### ISSUE TITLE
Set up and run a minimal working configuration

### ISSUE THREAD

**Issue by andrewgait** [UoMResearchIT/PhotonPropagation-Issue-Only#12]
In the Year 1 project, we worked with the so-called simplified RICH geometry, which would be a useful minimal working configuration. It consists of a photon source with configurable point of origin and direction (we ignored wavelength dependance), two mirrors and a detection plane in the shape of a pixelated rectangle. This is sufficiently non-trivial that we test photon transport and resolution on the detector side, but doesn't have other complications (e.g. we can assume that everything is in vacuum and we can thus ignore photon interactions with the medium they travel through).

_Originally posted by @gersabec in https://github.com/UoMResearchIT/PhotonPropagation-Issue-Only/issues/10#issuecomment-2124361499_

**Comment by andrewgait** [comment]
I am working on this issue; in particular, trying to figure out whether any of the current examples I have access to across various repositories reproduce this minimal configuration already.

**Comment by ianhinder** [comment]
(from discussion) This is a minimum working configuration of Mitsuba, based on obj files that have come from GDML files.

**Comment by andrewgait** [comment]
I would say this is complete in the sense that I have been able to run using the obj files available in Olivia's Mitsuba3 fork.  I am minded to close this as completed and continue working on #13 as part of the continuing work of understanding the minimal working configuration.

As part of this I think it would be sensible to be able to run the geometry conversion code to create an obj file and then run Mitsuba on this obj file to check everything works for me locally.
