### ISSUE TITLE
Store meeting notes in issues-only repository

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/PhotonPropagation-Issue-Only#2]
The "issues-only" repository is being used because there is no existing code repository which directly maps to RTP-215.  Should we use this repository also for storing project-specific documentation and notes?  e.g. the meeting notes I made today could be stored here.  We could also store architectural diagrams and designs etc here.

**Comment by andrewgait** [comment]
That sounds like a good idea to me - any notes relating to setting up / using Geant4 and Mitsuba 3 in particular should go in here.

**Comment by andrewgait** [comment]
I would suggest any notes should probably be added to the Wiki, just in case this repository ends up being renamed and used for code as well.  The documents we've just received on the project status as of January 2024 could also be added along with links to other repositories.

**Comment by ianhinder** [comment]
Sure, let's use the wiki for this. Depending on the nature of the documents, they could also go in Sharepoint.

**Comment by ianhinder** [comment]
Added meeting notes to https://github.com/UoMResearchIT/PhotonPropagation-Issue-Only/wiki/Meetings.
