### ISSUE TITLE
Understand how input and output works in Mitsuba 3

### ISSUE THREAD

**Issue by andrewgait** [UoMResearchIT/PhotonPropagation-Issue-Only#6]
Following running an example in #5, understand how Mitsuba 3's input and output work.

**Comment by andrewgait** [comment]
Some work was done towards this goal in the first sprint of the project, but more work is required to understand how the links between Geant4 and Mitsuba3 work.

**Comment by gersabec** [comment]
Olivia's code may be helpful for geometry conversion:
https://github.com/OliviaBorgstrom/mitsuba3-olivia/tree/master

**Comment by andrewgait** [comment]
Olivia's geometry conversion code is specifically mentioned in this comment: https://github.com/UoMResearchIT/PhotonPropagation-Issue-Only/issues/4#issuecomment-2124333160

It might be helpful if this code is put into a repository somewhere - I'm not sure that it is anywhere on GitHub at present.

**Comment by andrewgait** [comment]
Input into Mitsuba3 is done using object files (OBJ format). The conversion between the output GDML and OBJ is the focus of the conversion code mentioned in the previous comment and uses the pyg4ometry python package. pyg4ometry does not appear to work in Windows so some investigation of this in WSL seems sensible, which I will do as part of this issue.

Rendered output from Mitsuba3 in most cases so far has been a simple image displayed using matplotlib. I'm not sure whether any consideration has been made as to how output from Mitsuba3 needs to be fed back to Geant4 (or indeed, if this is even necessary).

**Comment by ianhinder** [comment]
I imagine that you will probably need more than just an image; maybe even the full traced rays for photon trajectories?

**Comment by gersabec** [comment]
Olivia's geometry code is available on my Dropbox: https://www.dropbox.com/scl/fo/rcqdxb1i0zuw4vprkqxrx/AAygQa0onHi8Lgc-Mc08Jjg?rlkey=6frg3t3o6d7w7tufeeqq904rc&dl=0
It would be great if you could include that into the repository.

Regarding output, yes, we'll need to feed back the photon hits to Geant4. There is a question of what stage this will happen at. One option is to use exact hit coordinates, another is to communicate in terms of the detector element that was hit (e.g. a sensor pixel address). The latter is more readily done from an image. For now, I would not prioritise the output side until input and rendering are under control.

**Comment by andrewgait** [comment]
> Olivia's geometry code is available on my Dropbox: https://www.dropbox.com/scl/fo/rcqdxb1i0zuw4vprkqxrx/AAygQa0onHi8Lgc-Mc08Jjg?rlkey=6frg3t3o6d7w7tufeeqq904rc&dl=0
> It would be great if you could include that into the repository.

I'm happy to do that - the question then, I suppose, is which repository we put it into, since it's not really part of Mitsuba - or would you envision it becoming part of Mitsuba in the future, and so adding it to Olivia's fork of Mitsuba is the best place to store it for now? The other option instead is to put it into this repository (and then rename this repository to PhotonPropagation because it's no longer an issue-only repo...).

**Comment by gersabec** [comment]
I think that question is precisely why it wasn't in any repository yet. Eventually, something like this will be required alongside Mitsuba, although it would likely remain separate from the Mitsuba code base. I'll leave it to your good judgement how to best organise that.

**Comment by ianhinder** [comment]
It should probably go into its own repository; it seems to be GEANT4-specific, but we don't maintain a fork of GEANT4, so its own repository sounds like the way to go.

**Comment by andrewgait** [comment]
Input to Mitsuba is covered by the work of the geometry conversion code (see #15).

Output from Mitsuba (to return to Geant4) will be considered in #16.
